/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psv;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;
import javax.swing.*;

public class JFCliente extends javax.swing.JFrame {

    public JFCliente() {
        initComponents();
        lblMensagemCliente.setText("");
        
        Connection con = Conexao.abrirConexao();
        ClienteDAO cd = new ClienteDAO(con);
        
        /*--------------------------------------------------------------------*/

        List<ClienteBean> listaCliente = new ArrayList<ClienteBean>();
        
        listaCliente = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaCliente.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (ClienteBean ub : listaCliente) {
            tbm.addRow(new String[1]);
            
            tbConsultaCliente.setValueAt(ub.getId(), i, 0);
            tbConsultaCliente.setValueAt(ub.getNome(), i, 1);
            tbConsultaCliente.setValueAt(ub.getTelResidencial(), i, 2);
            tbConsultaCliente.setValueAt(ub.getTelComercial(), i, 3);
            tbConsultaCliente.setValueAt(ub.getTelCelular(), i, 4);
            tbConsultaCliente.setValueAt(ub.getEmail(), i, 5);

            i++;
        }
        
        /*--------------------------------------------------------------------*/
        
        Conexao.fecharConexao(con);
        
    }

    public void atualizarBD() {
        /*--------------------------------------------------------------------*/
        Connection con = Conexao.abrirConexao();
        ClienteDAO cd = new ClienteDAO(con);
        List<ClienteBean> listaCliente = new ArrayList<ClienteBean>();
        
        listaCliente = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaCliente.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (ClienteBean ub : listaCliente) {
            tbm.addRow(new String[1]);
            
            tbConsultaCliente.setValueAt(ub.getId(), i, 0);
            tbConsultaCliente.setValueAt(ub.getNome(), i, 1);
            tbConsultaCliente.setValueAt(ub.getTelResidencial(), i, 2);
            tbConsultaCliente.setValueAt(ub.getTelComercial(), i, 3);
            tbConsultaCliente.setValueAt(ub.getTelCelular(), i, 4);
            tbConsultaCliente.setValueAt(ub.getEmail(), i, 5);

            i++;
        }
        Conexao.fecharConexao(con);
        
        /*--------------------------------------------------------------------*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelResidencial = new javax.swing.JLabel();
        txtTelResidencial = new javax.swing.JTextField();
        lblMensagemCliente = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblTelComercial = new javax.swing.JLabel();
        txtTelComercial = new javax.swing.JTextField();
        lblTelCelular = new javax.swing.JLabel();
        txtTelCelular = new javax.swing.JTextField();
        btnInserirCliente = new javax.swing.JButton();
        btnRemoverCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnConfirmarCliente = new javax.swing.JButton();
        btnCancelarCliente = new javax.swing.JButton();
        pnlConsultaUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlCentral.setBackground(new java.awt.Color(204, 204, 204));

        lblNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblEmail.setText("E-mail:");

        txtEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblTelResidencial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblTelResidencial.setText("Tel. Residencial:");

        txtTelResidencial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtTelResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelResidencialActionPerformed(evt);
            }
        });

        lblMensagemCliente.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblMensagemCliente.setText("Mensagem");

        lblNome1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblNome1.setText("ID:");

        txtID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtID.setEnabled(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblTelComercial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblTelComercial.setText("Tel. Comercial:");

        txtTelComercial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtTelComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelComercialActionPerformed(evt);
            }
        });

        lblTelCelular.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblTelCelular.setText("Tel. Celular:");

        txtTelCelular.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtTelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelCelularActionPerformed(evt);
            }
        });

        btnInserirCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInserirCliente.setText("Inserir");
        btnInserirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserirClienteMouseClicked(evt);
            }
        });
        btnInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirClienteActionPerformed(evt);
            }
        });

        btnRemoverCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRemoverCliente.setText("Remover");
        btnRemoverCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverClienteMouseClicked(evt);
            }
        });
        btnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarClienteMouseClicked(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConfirmarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConfirmarCliente.setText("Listar");
        btnConfirmarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarClienteMouseClicked(evt);
            }
        });

        btnCancelarCliente.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(lblMensagemCliente))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome1)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(txtNome)))
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelResidencial)
                                    .addComponent(txtTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGap(20, 20, 20)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelComercial)
                                    .addComponent(txtTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelCelular)))
                            .addComponent(txtEmail)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addComponent(btnInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemoverCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelResidencial)
                    .addComponent(lblTelComercial)
                    .addComponent(lblTelCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblEmail)
                .addGap(6, 6, 6)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lblMensagemCliente)
                .addGap(20, 20, 20))
        );

        pnlConsultaUsuario.setBackground(new java.awt.Color(204, 204, 204));

        tbConsultaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tel1", "Tel2", "Tel3", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbConsultaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbConsultaCliente);
        if (tbConsultaCliente.getColumnModel().getColumnCount() > 0) {
            tbConsultaCliente.getColumnModel().getColumn(0).setResizable(false);
            tbConsultaCliente.getColumnModel().getColumn(1).setResizable(false);
            tbConsultaCliente.getColumnModel().getColumn(2).setResizable(false);
            tbConsultaCliente.getColumnModel().getColumn(3).setResizable(false);
            tbConsultaCliente.getColumnModel().getColumn(4).setResizable(false);
            tbConsultaCliente.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pnlConsultaUsuarioLayout = new javax.swing.GroupLayout(pnlConsultaUsuario);
        pnlConsultaUsuario.setLayout(pnlConsultaUsuarioLayout);
        pnlConsultaUsuarioLayout.setHorizontalGroup(
            pnlConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlConsultaUsuarioLayout.setVerticalGroup(
            pnlConsultaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlConsultaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*    */
    private void btnInserirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirClienteMouseClicked
        // Inserindo valores no banco de dados
        Connection con = Conexao.abrirConexao();
        ClienteBean cb = new ClienteBean();
        ClienteDAO cd = new ClienteDAO(con);
        
        cb.setNome(txtNome.getText());
        cb.setTelResidencial(txtTelResidencial.getText());
        cb.setTelComercial(txtTelComercial.getText());
        cb.setTelCelular(txtTelCelular.getText());
        cb.setEmail(txtEmail.getText());
                
        lblMensagemCliente.setText(cd.inserirCliente(cb));
        
        /*--------------------------------------------------------------------*/
        
        List<ClienteBean> listaCliente = new ArrayList<ClienteBean>();
        
        listaCliente = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaCliente.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (ClienteBean ub : listaCliente) {
            tbm.addRow(new String[1]);
            
            tbConsultaCliente.setValueAt(ub.getId(), i, 0);
            tbConsultaCliente.setValueAt(ub.getNome(), i, 1);
            tbConsultaCliente.setValueAt(ub.getTelResidencial(), i, 2);
            tbConsultaCliente.setValueAt(ub.getTelComercial(), i, 3);
            tbConsultaCliente.setValueAt(ub.getTelCelular(), i, 4);
            tbConsultaCliente.setValueAt(ub.getEmail(), i, 5);

            i++;
        }
        
        /*--------------------------------------------------------------------*/
        
        Conexao.fecharConexao(con);

        txtID.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtTelResidencial.setText("");
        txtTelComercial.setText("");
        txtTelCelular.setText("");
        
    }//GEN-LAST:event_btnInserirClienteMouseClicked

    private void btnConfirmarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarClienteMouseClicked
    
    }//GEN-LAST:event_btnConfirmarClienteMouseClicked

    private void tbConsultaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaClienteMouseClicked
        // Passando os valores da linha da tabela para os campos

        Integer linha = tbConsultaCliente.getSelectedRow();
        
        int id = (int) tbConsultaCliente.getValueAt(linha, 0);
        String nome = (String) tbConsultaCliente.getValueAt(linha, 1);
        String telResidencial = (String) tbConsultaCliente.getValueAt(linha, 2);
        String telComercial = (String) tbConsultaCliente.getValueAt(linha, 3);
        String telCelular = (String) tbConsultaCliente.getValueAt(linha, 4);
        String email = (String) tbConsultaCliente.getValueAt(linha, 3);
        
        txtID.setText(String.valueOf(id));
        txtNome.setText(nome);
        txtTelResidencial.setText(telResidencial);
        txtTelComercial.setText(telComercial);
        txtTelCelular.setText(telCelular);
        txtEmail.setText(email);      

    }//GEN-LAST:event_tbConsultaClienteMouseClicked

    private void btnAlterarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarClienteMouseClicked
        // Alterando valores no banco de dados
        Connection con = Conexao.abrirConexao();
        
        ClienteBean cb = new ClienteBean();
        ClienteDAO cd = new ClienteDAO(con);
        
        cb.setNome(txtNome.getText());
        cb.setTelResidencial(txtTelResidencial.getText());
        cb.setTelComercial(txtTelComercial.getText());
        cb.setTelCelular(txtTelCelular.getText());
        cb.setEmail(txtEmail.getText());
        cb.setId(Integer.parseInt(txtID.getText()));
        
       
        lblMensagemCliente.setText(cd.alterarCliente(cb));
        
        /*--------------------------------------------------------------------*/
        
        List<ClienteBean> listaCliente = new ArrayList<ClienteBean>();
        
        listaCliente = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaCliente.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (ClienteBean ub : listaCliente) {
            tbm.addRow(new String[1]);
            
            tbConsultaCliente.setValueAt(ub.getId(), i, 0);
            tbConsultaCliente.setValueAt(ub.getNome(), i, 1);
            tbConsultaCliente.setValueAt(ub.getTelResidencial(), i, 2);
            tbConsultaCliente.setValueAt(ub.getTelComercial(), i, 3);
            tbConsultaCliente.setValueAt(ub.getTelCelular(), i, 4);
            tbConsultaCliente.setValueAt(ub.getEmail(), i, 5);

            i++;
        }
        
        /*--------------------------------------------------------------------*/
        
        Conexao.fecharConexao(con);
        
        txtID.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtTelResidencial.setText("");
        txtTelComercial.setText("");
        txtTelCelular.setText("");
        
    }//GEN-LAST:event_btnAlterarClienteMouseClicked

    private void btnRemoverClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverClienteMouseClicked
        // Excluindo registros da tabela no bd.
        Connection con = Conexao.abrirConexao();
        
        ClienteBean cb = new ClienteBean();
        ClienteDAO cd = new ClienteDAO(con);
        
        cb.setId(Integer.parseInt(txtID.getText()));

        //Cria um vetor de Objetos passando a opção de sim ou não
        Object[] opcoes = {"Sim", "Não"};
        
        int j = JOptionPane.showOptionDialog(
                null,
                "Deseja remover?",
                "Pergunta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (j == JOptionPane.YES_OPTION) {
            lblMensagemCliente.setText(cd.excluirCliente(cb));
        }
        
        /*--------------------------------------------------------------------*/
        
        List<ClienteBean> listaCliente = new ArrayList<ClienteBean>();
        
        listaCliente = cd.listarTodos();
        
        DefaultTableModel tbm = (DefaultTableModel) tbConsultaCliente.getModel();
        
        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        
        int i = 0;
        
        for (ClienteBean ub : listaCliente) {
            tbm.addRow(new String[1]);
            
            tbConsultaCliente.setValueAt(ub.getId(), i, 0);
            tbConsultaCliente.setValueAt(ub.getNome(), i, 1);
            tbConsultaCliente.setValueAt(ub.getTelResidencial(), i, 2);
            tbConsultaCliente.setValueAt(ub.getTelComercial(), i, 3);
            tbConsultaCliente.setValueAt(ub.getTelCelular(), i, 4);
            tbConsultaCliente.setValueAt(ub.getEmail(), i, 5);

            i++;
        }
        
        /*--------------------------------------------------------------------*/
        
        Conexao.fecharConexao(con);
        
        txtID.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtTelResidencial.setText("");
        txtTelComercial.setText("");
        txtTelCelular.setText("");

    }//GEN-LAST:event_btnRemoverClienteMouseClicked

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirClienteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtTelResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelResidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelResidencialActionPerformed

    private void txtTelComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelComercialActionPerformed

    private void btnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverClienteActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JFMenu jFMenu = new JFMenu();
        jFMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtTelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelCelularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JButton btnConfirmarCliente;
    private javax.swing.JButton btnInserirCliente;
    private javax.swing.JButton btnRemoverCliente;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMensagemCliente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblTelCelular;
    private javax.swing.JLabel lblTelComercial;
    private javax.swing.JLabel lblTelResidencial;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlConsultaUsuario;
    private javax.swing.JTable tbConsultaCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelCelular;
    private javax.swing.JTextField txtTelComercial;
    private javax.swing.JTextField txtTelResidencial;
    // End of variables declaration//GEN-END:variables
}
