/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psv;

import java.sql.*;
import javax.swing.*;

public class JFEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form JFEmpresa
     */
    public JFEmpresa() {
        initComponents();
        lblMensagemEmpresa.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentral = new javax.swing.JPanel();
        lblCodEmpresa = new javax.swing.JLabel();
        txtCodEmpresa = new javax.swing.JTextField();
        lblNomeEmpresa = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblMensagemEmpresa = new javax.swing.JLabel();
        btnLimparEmpresa = new javax.swing.JButton();
        btnInserirEmpresa = new javax.swing.JButton();
        btnExcluirEmpresa = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnListar2 = new javax.swing.JButton();
        esquerda1 = new javax.swing.JButton();
        esquerda2 = new javax.swing.JButton();
        direita2 = new javax.swing.JButton();
        direita = new javax.swing.JButton();
        lblCNPJ1 = new javax.swing.JLabel();
        pnlConsultaVeiculo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultaVeiculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlCentral.setBackground(new java.awt.Color(204, 204, 204));

        lblCodEmpresa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCodEmpresa.setText("Código Empresa:");

        txtCodEmpresa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblNomeEmpresa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblNomeEmpresa.setText("Nome da Empresa:");

        txtNomeEmpresa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblCNPJ.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCNPJ.setText("CNPJ:");

        txtCNPJ.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblRazaoSocial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblRazaoSocial.setText("Razão Social");

        txtRazaoSocial.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        lblMensagemEmpresa.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblMensagemEmpresa.setText("Mensagem");

        btnLimparEmpresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimparEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\limpar.png")); // NOI18N
        btnLimparEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparEmpresaMouseClicked(evt);
            }
        });
        btnLimparEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparEmpresaActionPerformed(evt);
            }
        });

        btnInserirEmpresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInserirEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\incluir.png")); // NOI18N
        btnInserirEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserirEmpresaMouseClicked(evt);
            }
        });
        btnInserirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirEmpresaActionPerformed(evt);
            }
        });

        btnExcluirEmpresa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnExcluirEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\apagar.png")); // NOI18N
        btnExcluirEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirEmpresaMouseClicked(evt);
            }
        });
        btnExcluirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEmpresaActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\listar2.png")); // NOI18N

        btnListar2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnListar2.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\listar.png")); // NOI18N

        esquerda1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        esquerda1.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\setaEsquerda.png")); // NOI18N

        esquerda2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        esquerda2.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\setaEsquerda2.png")); // NOI18N

        direita2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        direita2.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\setaDireita2.png")); // NOI18N

        direita.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        direita.setIcon(new javax.swing.ImageIcon("C:\\Users\\guilh\\Documents\\GitHub\\Java\\Atividade Final\\src\\psv\\icon\\setaDireita.png")); // NOI18N

        javax.swing.GroupLayout pnlCentralLayout = new javax.swing.GroupLayout(pnlCentral);
        pnlCentral.setLayout(pnlCentralLayout);
        pnlCentralLayout.setHorizontalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeEmpresa)
                            .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCNPJ))
                                .addGap(20, 20, 20)
                                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRazaoSocial)
                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCodEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCentralLayout.createSequentialGroup()
                                .addComponent(btnLimparEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnInserirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnExcluirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnListar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(esquerda1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(esquerda2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(direita2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(direita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCentralLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(lblMensagemEmpresa)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlCentralLayout.setVerticalGroup(
            pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esquerda1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esquerda2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direita2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblCodEmpresa)
                .addGap(6, 6, 6)
                .addComponent(txtCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblNomeEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(lblRazaoSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lblMensagemEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        lblCNPJ1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblCNPJ1.setText("Clínica");

        pnlConsultaVeiculo.setBackground(new java.awt.Color(204, 204, 204));

        tbConsultaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Dependente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbConsultaVeiculo);
        if (tbConsultaVeiculo.getColumnModel().getColumnCount() > 0) {
            tbConsultaVeiculo.getColumnModel().getColumn(0).setResizable(false);
            tbConsultaVeiculo.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout pnlConsultaVeiculoLayout = new javax.swing.GroupLayout(pnlConsultaVeiculo);
        pnlConsultaVeiculo.setLayout(pnlConsultaVeiculoLayout);
        pnlConsultaVeiculoLayout.setHorizontalGroup(
            pnlConsultaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlConsultaVeiculoLayout.setVerticalGroup(
            pnlConsultaVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConsultaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCNPJ1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblCNPJ1)
                .addGap(6, 6, 6)
                .addComponent(pnlConsultaVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparEmpresaMouseClicked
        // Limpando dados da janela
        txtCodEmpresa.setText("");
        txtNomeEmpresa.setText("");
        txtCNPJ.setText("");
        txtRazaoSocial.setText("");
        
        lblMensagemEmpresa.setText("");
        
    }//GEN-LAST:event_btnLimparEmpresaMouseClicked

    private void btnInserirEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirEmpresaMouseClicked
        // Inserindo valores no banco de dados
        Connection con = Conexao.abrirConexao();
        EmpresaBean cb = new EmpresaBean();
        EmpresaDAO cd = new EmpresaDAO(con);
        
        cb.setNomeEmpresa(txtNomeEmpresa.getText());
        cb.setCnpj(txtCNPJ.getText());
        cb.setRazaoSocial(txtRazaoSocial.getText());
        
        lblMensagemEmpresa.setText(cd.inserirEmpresa(cb));
        
        Conexao.fecharConexao(con);

    }//GEN-LAST:event_btnInserirEmpresaMouseClicked

    private void btnExcluirEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirEmpresaMouseClicked
        // Excluindo registros da tabela no bd.
        Connection con = Conexao.abrirConexao();
        
        EmpresaBean eb = new EmpresaBean();
        EmpresaDAO ed = new EmpresaDAO(con);
        
        eb.setCodEmpresa(Integer.parseInt(txtCodEmpresa.getText()));

        //Cria um vetor de Objetos passando a opção de sim ou não
        Object[] opcoes = {"Sim", "Não"};
        
        int i = JOptionPane.showOptionDialog(
                null,
                "Deseja excluir esse veículo: " + txtCodEmpresa.getText() + "?",
                "Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]);
        
        if (i == JOptionPane.YES_OPTION) {
            lblMensagemEmpresa.setText(ed.excluirEmpresa(eb));
        }
        
        Conexao.fecharConexao(con);

    }//GEN-LAST:event_btnExcluirEmpresaMouseClicked

    private void btnInserirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInserirEmpresaActionPerformed

    private void btnLimparEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparEmpresaActionPerformed

    private void btnExcluirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirEmpresa;
    private javax.swing.JButton btnInserirEmpresa;
    private javax.swing.JButton btnLimparEmpresa;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar2;
    private javax.swing.JButton direita;
    private javax.swing.JButton direita2;
    private javax.swing.JButton esquerda1;
    private javax.swing.JButton esquerda2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCNPJ1;
    private javax.swing.JLabel lblCodEmpresa;
    private javax.swing.JLabel lblMensagemEmpresa;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlConsultaVeiculo;
    private javax.swing.JTable tbConsultaVeiculo;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtCodEmpresa;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
